sudo: required
dist: trusty
language: rust
env:
  - PKG_CONFIG_PATH="/usr/lib/*/pkgconfig/"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pkg-config smbclient libsmbclient-dev
after_success: |
    cargo doc \
    && echo '<meta http-equiv=refresh content=0;url=smbclient-sys/index.html>' > target/doc/index.html && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
